### ISSUE TITLE
Nested digital objects not supported in Atom

### ISSUE THREAD

**Issue by axfelix** [artefactual-labs/agentarchives#48] opened 2018-11-21 21:44 UTC
Hi,

I notice that `Nested digital objects not supported` is listed as a limitation of the Atom codepaths in agentarchives right now -- how severe are the limitations preventing this, and is it planned to be worked on? We have a number of cases where we'd like to be posting metadata to nested digital objects, but based on your documentation and https://github.com/artefactual-labs/agentarchives/blob/master/agentarchives/atom/client.py#L588 I've concluded that there's probably no way to do it currently and it's not just confusing on our end.

**Comment by sevein** [comment] 2018-11-27 22:21
Hi @axfelix,

I think the problem is that Archivematica is not walking the tree recursively but just the immediate descendants. That's happening here: https://github.com/artefactual/archivematica/blob/stable/1.8.x/src/dashboard/src/components/archival_storage/atom.py#L79-L105 - definitely a feature that could be implemented.

I think the code you found was just trying to be very explicit about the lack of that particular entity in AtoM ([digital object components](https://github.com/archivesspace/archivesspace/blob/master/backend/app/model/digital_object_component.rb) - a tree of digital objects), but we can still reproduce a tree with any depth just using `add_child` and `add_digital_object` together.

**Comment by axfelix** [comment] 2018-11-28 00:05
That's good to know! I'm finding that when I'm trying to use this API to add metadata stubs to multi-part objects that have already been uploaded to Atom by doing something like

```
for dip_name in dip_names:
...
    client.add_digital_object(dip_name["slug"], title=dip_name["filename"], size=size, object_type=object_type, file_uuid=file_uuid)
```

It only appends the metadata to the first object.

**Comment by sevein** [comment] 2018-11-28 17:51
Ok, that makes sense but I can't see where the problem is. Can you provide a script that reproduces the issue so we can investigate further?

**Comment by axfelix** [comment] 2019-01-11 03:14
Hey, mind if I check in on this? We'd like to pursue API improvements if needed...

**Comment by axfelix** [comment] 2019-01-15 18:12
Hi @sevein,

It would be a case like this: https://atom.archives.sfu.ca/f-148-2-0-0-0-1

Where there are e.g. two sides of a cassette tape tied to a single item description.

**Comment by sevein** [comment] 2019-01-17 22:41
I've found that using `add_digital_object` more than once with the same `information_object_slug` does not error and in fact it creates extra digital objects associated to the same information object. I believe this is a bug in AtoM's API and it should be fixed! This may explain the problem that you're experiencing assuming that you have repeated values in `dip_name["slug"]` - would that be the case?

Here's an example of what I tried:

```python
# Create object "Foobar" to contain this test.
foobar_slug = client.add_child("faculty-of-law-fonds", "foobar")

# Create object "Sound Recording" as a child of "Foobar".
child_slug = client.add_child(parent_slug=foobar_slug, title="Sound Recording")

# Add side-a.wav to Sound Recording
client.add_digital_object(
    information_object_slug=child_slug, title="side-a.wav",
    uri="http://www.music.helsinki.fi/tmt/opetus/uusmedia/esim/a2002011001-e02-ulaw.wav")

# Add side-b.wav to Sound Recording
# THIS SHOULD ERROR BUT IT DOESN'T! ATOM'S API NEEDS TO BE FIXED (TBC).
client.add_digital_object(
    information_object_slug=child_slug, title="side-b.wav",
    uri="http://www.music.helsinki.fi/tmt/opetus/uusmedia/esim/a2002011001-e02-ulaw.wav")
```

Here's another example where every digital object has a dedicated information object: https://gist.github.com/sevein/1c19d63631658c87d4d475d9e221a926. This is how it's supposed to be done! I've been using https://demo.accesstomemory.org for my tests.

Also, I don't think `add_digital_object` is going to work to append extra metadata to existing digital objects. I don't think that'd be possible with the current AtoM API but it could definitely be updated.

Hopefully this clarifies the situation a bit and you can update your code

**Comment by axfelix** [comment] 2019-01-17 22:50
Yup, I think that's it right there (I may have tried it the other way initially and given up because I didn't understand the API well enough to identify that as a bug). Really glad to see an upstream bug confirmed here; happy to update my code when that's fixed.

**Comment by sevein** [comment] 2019-01-17 23:20
Ok, here's the bug in the AtoM project: https://projects.artefactual.com/issues/12728.

**Closed by sevein** 2019-01-17 23:20 UTC
